version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  node-tests:
    jobs:
      - node/test:
          version: 12.16.0
    steps:
      - checkout
      - run: cd code/nestjs && npm install
      - run: npm test
